### ISSUE TITLE
Invite current stable prometheus chart maintainers as collaborators with write access

### ISSUE THREAD

**Issue by scottrigby** [scottrigby/prometheus-helm-charts#12]
- [x] 1. We can start by adding a single GitHub [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) file to reproduce what the prow OWNERS files contain now. This can help with enabling [required reviews on pull requests](https://docs.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests)
- [x] 2. Then all collaborators can be invited with [write access](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization), without changing existing functionality from `stable`
~- [ ] 3. cleanup: remove the prow `OWNERS` files~ **Edit:** will be done as part of #14 so the initial helm index will be clean

## 📊 Maintainers poll
Do we want to keep this level of granularity, or would it be better to give all collaborators write access to all charts in this repo? Let's discuss in comments below…

**Comment by asherf** [comment]
👋

**Comment by scottrigby** [comment]
Invited all current maintainers as collaborators to this repo, and also pinged everyone in Slack ✅

**Comment by scottrigby** [comment]
Will close this issue for now since tasks are done ✅  but we can still comment here in the meantime if there is overwhelming concern about implementation and re-open if needed ⏳

**Comment by Xtigyro** [comment]
I believe we should keep the `OWNERS` file and the granularity because different people are involved in developing the different charts though closely related. 

I do think though that we should all have owners permissions regarding the repo. This shouldn't take from the actual permission to push commits/approve PRs for the different charts.

**Comment by scottrigby** [comment]
@Xtigyro after slack chat, I understand what you mean. OK so yes, keeping `CODEOWNERS` file as-is, but can not change access level until after repo transfer. Also open questions about effects of combining that access level with `CODEOWNERS` file. Added all that to a new issue, to be addressed after the transfer: https://github.com/scottrigby/prometheus-helm-charts/issues/20 Thanks!
