### ISSUE TITLE
Enabling required reviews on pull requests

### ISSUE THREAD

**Issue by scottrigby** [scottrigby/prometheus-helm-charts#15]
Do after #12

**Comment by scottrigby** [comment]
Added ✅ 

Here are the `main` branch protection rules, for future ref:

![screencapture-github-scottrigby-prometheus-helm-charts-settings-branch-protection-rules-17224145-2020-08-19-12_07_47](https://user-images.githubusercontent.com/407675/90661127-cf198180-e214-11ea-9728-d43556fd7be5.png)

Note we don't enable branch protection on the GitHub pages branch used for helm repo indexing, because `helm/chart-releaser-action` force-pushes to keep things fully automated: https://github.com/helm/chart-releaser-action/blob/97237943efb7a48269d47a642ec5fdff675aa55f/cr.sh#L235

**Comment by Xtigyro** [comment]
Could we include please `admistrators`?

**Comment by scottrigby** [comment]
@Xtigyro done ✅
